# Generated by cpputils-cmake.
include /Users/Winmad/Projects/PointContour/build/CMakeFiles/PointContour.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES}  -S ${CHK_SOURCES}