#define OUTPUT_MESH_IN_CURVE 0
#define OUTPUT_MESH 0
#define OUTPUT_CURVE_NET 0
#define OUTPUT_CURVE_NET_WITH_NORMAL 0
#define OUTPUT_DIST_FIELD 0
#define OUTPUT_TRANSFORMED_PC 0

#define PC_NOT_NEED_TRANSFORM 0